version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DEV}
    env_file:
      - .env
    volumes:
      - 'app-volume:/var/lib/postgresql/data'

volumes:
  app-volume:
